apiVersion: v1
kind: Service
metadata:
  name: llm-multi-agent-backend
spec:
  selector:
    app: llm-multi-agent-backend
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  type: ClusterIP
