# /rag_multi_agent_project/manifests/02-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: llm-app-backend
type: Opaque
data:
  # 중요: 아래 값들은 'echo -n "실제값" | base64' 명령어로 인코딩해야 합니다.
  
  # --- OPEN AI ---
  OPENAI_API_KEY: "c2stcHJvai1Kc0hBbUx0Xy10WElrZm5BLVotR3I5VUZUaTM0YUt1WWZNeUNYbVBUMHlRTnI0ODdRWUN0cGtoRHRXa1luSmlmS0ZscENUTWNyYVQzQmxia0ZKUUV6UkliejJsVE9xa2k3alpjMVlucm8tOVFzeDk0eGhHbVlhMkhhM0hLVDdhY3Y1V1lBVVFIS0FDXzY3WXdlenBual9GaEdKWUE=" # 실제 키를 인코딩한 값
  
  # --- Google Gemini ---
  GEMINI_API_KEY: "QUl6YVN5QnRTNVoxQTZMcnVTSEJzV01pOG9UTTYwTGMwV0R5U0E0" # 실제 키를 인코딩한 값
  
  # --- NAVER NEWS ---
  NAVER_CLIENT_ID: "akZnT0xZSDhnVUZRMl8wRGhla1E=" # 실제 ID를 인코딩한 값
  NAVER_CLIENT_SECRET: "WTF4cWVaWmZGNA==" # 실제 Secret을 인코딩한 값
  
  # --- NCP Object Storage ---
  NCP_ACCESS_KEY: "bmNwX2lhbV9CUEFNS1I4N0JVUTFrYmRVM0xEdw==" # 실제 키를 인코딩한 값
  NCP_SECRET_KEY: "bmNwX2lhbV9CUEtNS1JMczlWSlI2Z2Z6bE5WeWFUbzhGcDVqV2RCT1NV" # 실제 키를 인코딩한 값
  
  # --- DATABASE (Supabase) ---
  # DATABASE_URL: "cG9zdGdyZXNxbDovL3Bvc3RncmVzOkVRZEFBVktqVmRCOUZpTmtAZGIuYmh4d2l2a21vdm1ncHRtdXR0YmIuc3VwYWJhc2UuY286NTQzMi9wb3N0Z3Jlcw==" # 실제 URL을 인코딩한 값
  DATABASE_URL: "cG9zdGdyZXNxbDovL3Bvc3RncmVzLmJoeHdpdmttb3ZtZ3B0bXV0dGJiOkVRZEFBVktqVmRCOUZpTmtAYXdzLTEtYXAtc291dGhlYXN0LTEucG9vbGVyLnN1cGFiYXNlLmNvbTo2NTQzL3Bvc3RncmVz" 
